from pydantic import BaseModel, Field
from typing import List, Union
import uuid


class MinimalSource(BaseModel):
    """
    Represent a minimal source reference from a document.

    Attributes:
        file_path (str): Path to the file
        first_character_index (int): Start index of the relevant excerpt.
        last_character_index (int): End inde of the relevant excerpt.
    """
    file_path: str
    first_character_index: int
    last_character_index: int


class UnansweredQuestion(BaseModel):
    """
    Represent a question without an answer and retrieved sources.

    Attributes:
        question_id (str): Unique identifier (auto-generated if not provided).
        question_str (str): Question text.
    """
    question_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    question_str: str


class AnsweredQuestion(UnansweredQuestion):
    """
    Represent a question with an answer and its retrieved sources.

    Attributes:
        sources (List[MinimalSource]): Retrieved sources from the question.
        answer (str): Answer to the question.
    """
    sources: List[MinimalSource]
    answer: str


class RagDataset(BaseModel):
    """
    Represent a dataset of RAG questions.

    Attributes:
        rag_questions (List[Union[AnsweredQuestion, UnansweredQuestion]): List
            of questions, either answered or unanswered.
    """
    rag_questions: List[Union[AnsweredQuestion, UnansweredQuestion]]


class MinimalSearchResults(BaseModel):
    """
    Reprensent a minimal search results from a question.

    Attributes:
        question_id (str): Unique identifier.
        question_str (str): Question text.
        retrieved_sources (List[MinimalSource]): List of question-related
            retrieved sources.
    """
    question_id: str
    question_str: str
    retrieved_sources: List[MinimalSource]


class MinimalAnswer(MinimalSearchResults):
    """
    Represent a search result enriched with a generated answer.

    Attributes:
        answer (str): The answer generated by the LLM.
    """
    answer: str


class StudentSearchResultsBase(BaseModel):
    """
    Represent a base for a student search results.

    Attributes:
        k (int): Number of retrieved sources per query.
    """
    k: int


class StudentSearchResults(StudentSearchResultsBase):
    """
    Collection of search results for multiple queries.

    Attributes:
        search_results (List[MinimalSearchResults]): List of search results.
    """
    search_results: List[MinimalSearchResults]


class StudentSearchResultsAndAnswer(StudentSearchResultsBase):
    """
    Collection of search results with answers for multiple queries.

    Attributes:
        search_results (List[MinimalAnswer]): List of search results enriched
            with answers, one per query.
    """
    search_results: List[MinimalAnswer]
